export const syllabusKids = {
  1: {
    title: "Challenge 1",
    desc: "Introduce yourself in English k (video or audio)",
  },
  2: { title: "Challenge 2", desc: "Basic vocabulary: colors and numbers k" },
  3: { title: "Challenge 3", desc: "Family members presentation k" },
  4: { title: "Challenge 4", desc: "Daily routine description k" },
  5: {
    title: "Milestone 5",
    desc: "Complete a full conversation practice k",
  },
  6: { title: "Challenge 6", desc: "Descripción del Challenge" },
  7: { title: "Challenge 7", desc: "Descripción del Challenge" },
  8: { title: "Challenge 8", desc: "Descripción del Challenge" },
  9: { title: "Challenge 9", desc: "Descripción del Challenge" },
  10: { title: "Milestone 10", desc: "Complete a full conversation practice" },
  11: { title: "Challenge 11", desc: "Descripción del Challenge" },
  12: { title: "Challenge 12", desc: "Descripción del Challenge" },
  13: { title: "Challenge 13", desc: "Descripción del Challenge" },
  14: { title: "Challenge 14", desc: "Descripción del Challenge" },
  15: {
    title: "Milestone 15",
    desc: "Complete your first full conversation practice",
  },
  16: { title: "Challenge 16", desc: "Descripción del Challenge" },
  17: { title: "Challenge 17", desc: "Descripción del Challenge" },
  18: { title: "Challenge 18", desc: "Descripción del Challenge" },
  19: { title: "Challenge 19", desc: "Descripción del Challenge" },
  20: {
    title: "Milestone 20",
    desc: "Complete your first full conversation practice",
  },
  21: { title: "Challenge 21", desc: "Descripción del Challenge" },
  22: { title: "Challenge 22", desc: "Descripción del Challenge" },
  23: { title: "Challenge 23", desc: "Descripción del Challenge" },
  24: { title: "Challenge 24", desc: "Descripción del Challenge" },
  25: {
    title: "Milestone 25",
    desc: "Complete your first full conversation practice",
  },
  26: { title: "Challenge 26", desc: "Descripción del Challenge" },
  27: { title: "Challenge 27", desc: "Descripción del Challenge" },
  28: { title: "Challenge 28", desc: "Descripción del Challenge" },
  29: { title: "Challenge 29", desc: "Descripción del Challenge" },
  30: {
    title: "FINAL GRAND PRIZE",
    desc: "Complete the full course challenge and receive your  Grand Prize!",
  },
};
